modmap:
  - name: Global
    remap:
      CapsLock:
        held: Ctrl_L
        alone: Esc

keymap:
  - name: Global
    remap:
      Super-Ctrl-LeftBrace: Ctrl-Shift-Tab
      Super-Ctrl-RightBrace: Ctrl-Tab
